adabtb configure script
git-svn-id: file:///home/amuse/svn/amuse/trunk@3111 6e832d89-e7d1-4ad1-8ca1-873beecccf65

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -683,6 +683,14 @@ GSL_CFLAGS
 HDF5_LIBS
 HDF5_FLAGS
 FOUND_HDF5
+MPFR_FLAGS
+FOUND_MPFR
+MPFR_LIBS
+MPFR_CFLAGS
+GMP_FLAGS
+FOUND_GMP
+GMP_LIBS
+GMP_CFLAGS
 FFTW_FLAGS
 FOUND_FFTW
 EGREP
@@ -780,6 +788,8 @@ with_cuda_libdir
 with_sapporo
 enable_sapporo2
 with_fftw
+with_gmp
+with_mpfr
 with_hdf5
 with_gsl_prefix
 with_gsl_exec_prefix
@@ -811,6 +821,10 @@ PKG_CONFIG_LIBDIR
 FFTW_CFLAGS
 FFTW_LIBS
 CPP
+GMP_CFLAGS
+GMP_LIBS
+MPFR_CFLAGS
+MPFR_LIBS
 GSL_CFLAGS
 GSL_LIBS'
 
@@ -1440,6 +1454,8 @@ Optional Packages:
   --with-cuda-libdir=PFX   Directory where libcuda.so is installed (optional)
   --with-sapporo          Use sapporo library in given directory
   --with-fftw=PFX         Prefix where FFTW has been installed
+  --with-gmp=PFX          Prefix where GMP has been installed
+  --with-mpfr=PFX         Prefix where MPFR has been installed
   --with-hdf5=PFX         Prefix where HDF5 has been installed
   --with-gsl=PFX   Prefix where GSL is installed (optional)
   --with-gsl-exec-prefix=PFX Exec prefix where GSL is installed (optional)
@@ -1471,6 +1487,10 @@ Some influential environment variables:
   FFTW_CFLAGS C compiler flags for FFTW, overriding pkg-config
   FFTW_LIBS   linker flags for FFTW, overriding pkg-config
   CPP         C preprocessor
+  GMP_CFLAGS  C compiler flags for GMP, overriding pkg-config
+  GMP_LIBS    linker flags for GMP, overriding pkg-config
+  MPFR_CFLAGS C compiler flags for MPFR, overriding pkg-config
+  MPFR_LIBS   linker flags for MPFR, overriding pkg-config
   GSL_CFLAGS  C compiler flags for GSL, overriding pkg-config
   GSL_LIBS    linker flags for GSL, overriding pkg-config
 
@@ -6339,6 +6359,540 @@ $as_echo "yes" >&6; }
 
 
 fi
+
+
+
+
+# Check whether --with-gmp was given.
+if test "${with_gmp+set}" = set; then :
+  withval=$with_gmp;
+                test "$withval" = no && { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: gmp is a required package for some modules" >&5
+$as_echo "$as_me: WARNING: gmp is a required package for some modules" >&2;}
+                test "$withval" = yes || gmp_prefix="$withval"
+                with_gmp=yes
+else
+   with_gmp=yes
+
+fi
+
+
+        if test "x$with_gmp" != xno ; then :
+
+            #user override
+            if test "x$GMP_LIBS" != x ; then :
+
+                have_gmp=yes
+                FOUND_GMP="yes"
+
+else
+
+
+
+
+                saved_LIBS="$LIBS"
+                saved_CXXFLAGS="$CXXFLAGS"
+                GMP_LIBS=""
+                GMP_FLAGS=""
+                FOUND_GMP="no"
+                if test x$gmp_prefix == x; then
+                   if test x$PREFIX != x; then
+		                gmp_prefix=$PREFIX
+                   fi
+                fi
+                if test x$gmp_prefix != x; then
+                    ac_gmp_CFLAGS="-I$gmp_prefix/include"
+                    ac_gmp_LDOPTS="-L$gmp_prefix/lib"
+
+
+                    save_CFLAGS="$CFLAGS"
+                    save_CPPFLAGS="$CPPFLAGS"
+                    CFLAGS="$ac_gmp_CFLAGS $save_CFLAGS"
+                    CPPFLAGS="$ac_gmp_CFLAGS $save_CPPFLAGS"
+                    ac_fn_c_check_header_mongrel "$LINENO" "gmp.h" "ac_cv_header_gmp_h" "$ac_includes_default"
+if test "x$ac_cv_header_gmp_h" = xyes; then :
+  GMP_FLAGS="$ac_gmp_CFLAGS"
+                        FOUND_GMP="yes"
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot find headers (gmp.h) of the library GMP in $gmp_prefix/include." >&5
+$as_echo "$as_me: WARNING: Cannot find headers (gmp.h) of the library GMP in $gmp_prefix/include." >&2;}
+
+fi
+
+
+                    CFLAGS="$save_CFLAGS"
+                    CPPFLAGS="$save_CPPFLAGS"
+
+	                if test x$FOUND_GMP == xyes; then
+                        save_LIBS="$LIBS"
+                        LIBS="$ac_gmp_LDOPTS -lgmp $save_LIBS"
+                        { $as_echo "$as_me:${as_lineno-$LINENO}: checking for __gmpz_init in -lgmp" >&5
+$as_echo_n "checking for __gmpz_init in -lgmp... " >&6; }
+if ${ac_cv_lib_gmp___gmpz_init+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgmp  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char __gmpz_init ();
+int
+main ()
+{
+return __gmpz_init ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_gmp___gmpz_init=yes
+else
+  ac_cv_lib_gmp___gmpz_init=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_gmp___gmpz_init" >&5
+$as_echo "$ac_cv_lib_gmp___gmpz_init" >&6; }
+if test "x$ac_cv_lib_gmp___gmpz_init" = xyes; then :
+  GMP_LIBS="$ac_gmp_LDOPTS -lgmp"
+else
+  FOUND_GMP="no"
+                            { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: libgmp : library missing. (Cannot find symbol gmpz_init) in $gmp_prefix. Check if libgmp is installed and if the version is correct" >&5
+$as_echo "$as_me: WARNING: libgmp : library missing. (Cannot find symbol gmpz_init) in $gmp_prefix. Check if libgmp is installed and if the version is correct" >&2;}
+
+fi
+
+                        LIBS="$save_LIBS"
+                    fi
+	fi
+	if test x$FOUND_GMP != xyes; then
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GMP" >&5
+$as_echo_n "checking for GMP... " >&6; }
+
+if test -n "$GMP_CFLAGS"; then
+    pkg_cv_GMP_CFLAGS="$GMP_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gmp >= 3\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gmp >= 3") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GMP_CFLAGS=`$PKG_CONFIG --cflags "gmp >= 3" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GMP_LIBS"; then
+    pkg_cv_GMP_LIBS="$GMP_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gmp >= 3\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gmp >= 3") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GMP_LIBS=`$PKG_CONFIG --libs "gmp >= 3" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GMP_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "gmp >= 3" 2>&1`
+        else
+	        GMP_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "gmp >= 3" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GMP_PKG_ERRORS" >&5
+
+
+
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+
+else
+	GMP_CFLAGS=$pkg_cv_GMP_CFLAGS
+	GMP_LIBS=$pkg_cv_GMP_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+                    GMP_FLAGS="$GMP_FLAGS"
+                    GMP_LIBS="$GMP_LIBS"
+                    FOUND_GMP=yes
+
+fi
+
+    fi
+
+	if test x$FOUND_GMP != xyes; then
+                    ac_fn_c_check_header_mongrel "$LINENO" "gmp.h" "ac_cv_header_gmp_h" "$ac_includes_default"
+if test "x$ac_cv_header_gmp_h" = xyes; then :
+  GMP_FLAGS=""
+                        FOUND_GMP="yes"
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot find headers (gmp.h) of the library GMP." >&5
+$as_echo "$as_me: WARNING: Cannot find headers (gmp.h) of the library GMP." >&2;}
+
+fi
+
+
+                    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for __gmpz_init in -lgmp" >&5
+$as_echo_n "checking for __gmpz_init in -lgmp... " >&6; }
+if ${ac_cv_lib_gmp___gmpz_init+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgmp  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char __gmpz_init ();
+int
+main ()
+{
+return __gmpz_init ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_gmp___gmpz_init=yes
+else
+  ac_cv_lib_gmp___gmpz_init=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_gmp___gmpz_init" >&5
+$as_echo "$ac_cv_lib_gmp___gmpz_init" >&6; }
+if test "x$ac_cv_lib_gmp___gmpz_init" = xyes; then :
+  GMP_LIBS="-lgmp"
+else
+
+                        FOUND_GMP="no"
+                        { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: libgmp : library missing. (Cannot find symbol gmpz_init). Check if libgmp is installed and if the version is correct" >&5
+$as_echo "$as_me: WARNING: libgmp : library missing. (Cannot find symbol gmpz_init). Check if libgmp is installed and if the version is correct" >&2;}
+
+fi
+
+		fi
+
+
+
+fi
+
+fi
+
+
+
+
+
+
+
+
+# Check whether --with-mpfr was given.
+if test "${with_mpfr+set}" = set; then :
+  withval=$with_mpfr;
+                test "$withval" = no && { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: mpfr is a required package for some modules" >&5
+$as_echo "$as_me: WARNING: mpfr is a required package for some modules" >&2;}
+                test "$withval" = yes || mpfr_prefix="$withval"
+                with_mpfr=yes
+else
+   with_mpfr=yes
+
+fi
+
+
+        if test "x$with_mpfr" != xno ; then :
+
+            #user override
+            if test "x$MPFR_LIBS" != x ; then :
+
+                have_mpfr=yes
+                FOUND_MPFR="yes"
+
+else
+
+
+
+
+                saved_LIBS="$LIBS"
+                saved_CXXFLAGS="$CXXFLAGS"
+                MPFR_LIBS=""
+                MPFR_FLAGS=""
+                FOUND_MPFR="no"
+                if test x$mpfr_prefix == x; then
+                   if test x$PREFIX != x; then
+		                mpfr_prefix=$PREFIX
+                   fi
+                fi
+                if test x$mpfr_prefix != x; then
+                    ac_mpfr_CFLAGS="-I$mpfr_prefix/include"
+                    ac_mpfr_LDOPTS="-L$mpfr_prefix/lib"
+
+
+                    save_CFLAGS="$CFLAGS"
+                    save_CPPFLAGS="$CPPFLAGS"
+                    CFLAGS="$ac_mpfr_CFLAGS $save_CFLAGS"
+                    CPPFLAGS="$ac_mpfr_CFLAGS $save_CPPFLAGS"
+
+                    cache_var=ac_cv_header_mpfr_h
+                    ac_fn_c_check_header_mongrel "$LINENO" "mpfr.h" "ac_cv_header_mpfr_h" "$ac_includes_default"
+if test "x$ac_cv_header_mpfr_h" = xyes; then :
+  MPFR_FLAGS="$ac_mpfr_CFLAGS"
+                        FOUND_MPFR="yes"
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot find headers (mpfr.h) of the library MPFR in $mpfr_prefix/include." >&5
+$as_echo "$as_me: WARNING: Cannot find headers (mpfr.h) of the library MPFR in $mpfr_prefix/include." >&2;}
+
+fi
+
+
+                    $as_unset $cache_var
+                    CFLAGS="$save_CFLAGS"
+                    CPPFLAGS="$save_CPPFLAGS"
+
+	                if test x$FOUND_MPFR == xyes; then
+                        save_LIBS="$LIBS"
+                        LIBS="$ac_mpfr_LDOPTS -lmpfr $save_LIBS"
+
+                        cache_var=ac_cv_lib_mpfr_mpfr_init
+                        { $as_echo "$as_me:${as_lineno-$LINENO}: checking for mpfr_init in -lmpfr" >&5
+$as_echo_n "checking for mpfr_init in -lmpfr... " >&6; }
+if ${ac_cv_lib_mpfr_mpfr_init+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmpfr  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char mpfr_init ();
+int
+main ()
+{
+return mpfr_init ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_mpfr_mpfr_init=yes
+else
+  ac_cv_lib_mpfr_mpfr_init=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_mpfr_mpfr_init" >&5
+$as_echo "$ac_cv_lib_mpfr_mpfr_init" >&6; }
+if test "x$ac_cv_lib_mpfr_mpfr_init" = xyes; then :
+  MPFR_LIBS="$ac_mpfr_LDOPTS -lmpfr"
+else
+  FOUND_MPFR="no"
+                            { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: libmpfr : library missing. (Cannot find symbol mpfr_init) in $mpfr_prefix. Check if libmpfr is installed and if the version is correct" >&5
+$as_echo "$as_me: WARNING: libmpfr : library missing. (Cannot find symbol mpfr_init) in $mpfr_prefix. Check if libmpfr is installed and if the version is correct" >&2;}
+
+fi
+
+                        LIBS="$save_LIBS"
+                        $as_unset $cache_var
+                    fi
+	fi
+	if test x$FOUND_MPFR != xyes; then
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for MPFR" >&5
+$as_echo_n "checking for MPFR... " >&6; }
+
+if test -n "$MPFR_CFLAGS"; then
+    pkg_cv_MPFR_CFLAGS="$MPFR_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"mpfr >= 3\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "mpfr >= 3") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_MPFR_CFLAGS=`$PKG_CONFIG --cflags "mpfr >= 3" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$MPFR_LIBS"; then
+    pkg_cv_MPFR_LIBS="$MPFR_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"mpfr >= 3\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "mpfr >= 3") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_MPFR_LIBS=`$PKG_CONFIG --libs "mpfr >= 3" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        MPFR_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "mpfr >= 3" 2>&1`
+        else
+	        MPFR_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "mpfr >= 3" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$MPFR_PKG_ERRORS" >&5
+
+
+
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+
+else
+	MPFR_CFLAGS=$pkg_cv_MPFR_CFLAGS
+	MPFR_LIBS=$pkg_cv_MPFR_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+                    MPFR_FLAGS="$MPFR_FLAGS"
+                    MPFR_LIBS="$MPFR_LIBS"
+                    FOUND_MPFR=yes
+
+fi
+
+    fi
+
+	if test x$FOUND_MPFR != xyes; then
+                    ac_fn_c_check_header_mongrel "$LINENO" "mpfr.h" "ac_cv_header_mpfr_h" "$ac_includes_default"
+if test "x$ac_cv_header_mpfr_h" = xyes; then :
+  MPFR_FLAGS=""
+                        FOUND_MPFR="yes"
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot find headers (mpfr.h) of the library MPFR." >&5
+$as_echo "$as_me: WARNING: Cannot find headers (mpfr.h) of the library MPFR." >&2;}
+
+fi
+
+
+                    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for mpfr_init in -lmpfr" >&5
+$as_echo_n "checking for mpfr_init in -lmpfr... " >&6; }
+if ${ac_cv_lib_mpfr_mpfr_init+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmpfr  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char mpfr_init ();
+int
+main ()
+{
+return mpfr_init ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_mpfr_mpfr_init=yes
+else
+  ac_cv_lib_mpfr_mpfr_init=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_mpfr_mpfr_init" >&5
+$as_echo "$ac_cv_lib_mpfr_mpfr_init" >&6; }
+if test "x$ac_cv_lib_mpfr_mpfr_init" = xyes; then :
+  MPFR_LIBS="-lmpfr"
+else
+
+                        FOUND_MPFR="no"
+                        { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: libmpfr : library missing. (Cannot find symbol mpfr_init). Check if libmpfr is installed and if the version is correct" >&5
+$as_echo "$as_me: WARNING: libmpfr : library missing. (Cannot find symbol mpfr_init). Check if libmpfr is installed and if the version is correct" >&2;}
+
+fi
+
+		fi
+
+
+
+fi
+
+fi
+
+
+
+
 
 
 
